set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(SDK_HOST "/tmp/tg5050-sdk/host")
set(CMAKE_C_COMPILER "${SDK_HOST}/bin/aarch64-none-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "${SDK_HOST}/bin/aarch64-none-linux-gnu-g++")
set(CMAKE_AR "${SDK_HOST}/bin/aarch64-none-linux-gnu-ar")
set(CMAKE_RANLIB "${SDK_HOST}/bin/aarch64-none-linux-gnu-ranlib")
set(CMAKE_STRIP "${SDK_HOST}/bin/aarch64-none-linux-gnu-strip")
set(CMAKE_SYSROOT "${SDK_HOST}/aarch64-buildroot-linux-gnu/sysroot")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(PKG_CONFIG_EXECUTABLE "${SDK_HOST}/bin/pkg-config" CACHE FILEPATH "")
